notifications:
  email: false
language: rust
rust:
  - stable
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --test-threads=1
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
