[package]
name = "grace"
version = "0.1.0"
authors = ["Vincent Luczkow <vincent.luczkow@gmail.com>",
           "Miranda Gavrin <mirandagavrin@gmail.com"]

[dependencies]
nom = "~3"
libc = "*"
log = "0.4"
cute = "*"
rand = "*"
itertools = "*"


[lib]
name = "grace_lib"
doctest = false

[[bin]]
name = "grace_main"
path = "src/bin.rs"
