version: 2.1
orbs:
  python: circleci/rust@1.6.0
commands:
  run_tests:
    steps:
        - checkout
        - run:
            name: Install
            command: pip install .[dev]
        - run:
            name: Run tests
            command: pytest tests/

jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Build
          command: cargo build
  test:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Test
          command: cargo test

workflows:
  build_and_test_workflow:
    jobs:
      - build
      - test
