fn conditional(a, b):
    if 0:
        return a
    else:
        return b

fn add(a, b):
    let x = a + b
    return x

fn sub(a, b):
    let x = a - b
    return x

fn mult(a, b):
    let x = a * b
    return x

fn div(a, b):
    let x = a / b
    return x

fn loop(x, y):
    while x > y:
        x = x - 1
    return x

fn equality(a, b):
    return a == b

fn neq(a, b):
    return a != b

fn less(a, b):
    return a < b

fn lesse(a, b):
    return a <= b

fn great(a, b):
    return a > b

fn greate(a, b):
    return a >= b
