use std::fmt::Display;

use expression::*;

//#[derive(Debug, Clone, PartialEq, Eq, Hash)]
//pub enum Scoped {
//    Module(Module),
//    Block(Block),
//    Statement(Stmt),
//    Expression(Expr)
//}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CanModifyScope {
    Statement(Stmt),
    Expression(Expr)
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Scope {
    pub parent_scope: Box<Scope>,
    pub declarations: Vec<(Identifier, CanModifyScope)>
}

pub trait Scoped {
    fn get_scope(&self, parent_scope: Scope) -> Scope;
}

pub trait ASTNode: Display {
    /// Generate WAST bytecode from an AST
    /// CONVENTIONS:
    ///     Generated bytecode should not start or end with a newline, *except* for modules / other
    ///     top level functions. Starting and ending newlines are the responsibility of the parent
    ///     node. We don't have to do it this way, but it's important to have a single convention.
    ///     Nodes *do* need to handle newlines at the start and end of their *children*, obviously.
    fn generate_bytecode(&self) -> String;


}
